const VIETNAM_PROVINCES = {
  AN_GIANG: "An Giang",
  BAC_GIANG: "Bac Giang",
  BAC_KAN: "Bac Kan",
  BAC_LIEU: "Bac Lieu",
  BAC_NINH: "Bac Ninh",
  BEN_TRE: "Ben Tre",
  CAO_BANG: "Cao Bang",
  DAK_LAK: "Dak Lak",
  DAK_NON: "Dak Nong",
  DIEN_BIEN: "Dien Bien",
  DONG_NAI: "Dong Nai",
  HA_GIANG: "Ha Giang",
  HAI_DUONG: "Hai Duong",
  HAI_PHONG: "Hai Phong",
  HA_NAM: "Ha Nam",
  HA_NOI: "Ha Noi",
  HA_TINH: "Ha Tinh",
  HOA_BINH: "Hoa Binh",
  HUYEN_THAI: "Huyen Thai",
  LAO_CAI: "Lao Cai",
  LANG_SON: "Lang Son",
  NAM_DINH: "Nam Dinh",
  NINH_BINH: "Ninh Binh",
  PHU_THO: "Phu Tho",
  PHU_YEN: "Phu Yen",
  QUANG_BINH: "Quang Binh",
  QUANG_NINH: "Quang Ninh",
  SON_LA: "Son La",
  THAI_BINH: "Thai Binh",
  THAI_NGUYEN: "Thai Nguyen",
  THANH_HOA: "Thanh Hoa",
  TUYEN_QUANG: "Tuyen Quang",
  YEN_BAI: "Yen Bai",

  BINH_DINH: "Binh Dinh",
  BINH_DUONG: "Binh Duong",
  BINH_THUAN: "Binh Thuan",
  DA_NANG: "Da Nang",
  GIA_LAI: "Gia Lai",
  KHANH_HOA: "Khanh Hoa",
  NINH_THUAN: "Ninh Thuan",
  QUANG_NGAI: "Quang Ngai",
  QUANG_TRI: "Quang Tri",
  THUA_THIEN_HUE: "Thua Thien Hue",

  AG_GIA_RAI: "AG Gia Lai",
  BA_RIA_VUNG_TAU: "Ba Ria Vung Tau",
  BAC_THU: "Bac Thu",
  CA_MAU: "Ca Mau",
  CAN_THO: "Can Tho",
  DAU_TIENG: "Dau Tieng",
  DONG_THAP: "Dong Thap",
  HO_CHI_MINH: "Ho Chi Minh",
  KIEN_GIANG: "Kien Giang",
  LONG_AN: "Long An",
  QUANG_NAM: "Quang Nam",
  QUANG_NGUYEN: "Quang Ngai",
  SOC_TRANG: "Soc Trang",
  TAY_NINH: "Tay Ninh",
  TIEN_GIANG: "Tien Giang",
  VINH_LONG: "Vinh Long",
  VUNG_TAU: "Vung Tau",
  LAM_DONG: "Lam Dong",
};

module.exports = { PROVINCES: Object.keys(VIETNAM_PROVINCES) };
